import Link from 'next/link'
import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata = {
  title: 'Front-end Insights',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={poppins.className}>
        <div className="flex min-h-screen flex-col items-center justify-between max-w-5xl mx-auto px-5">
          <header className="flex items-center justify-between w-full py-10 flex-wrap gap-x-3">
            <span className="text-2xl font-black cursor-default">INSIGHTS</span>
            <nav className="flex gap-10 [&>a:hover]:text-gray-300">
              <Link href="/">Início</Link>
              <Link href="/about">Sobre</Link>
              <Link href="/subscribers">Inscritos</Link>
            </nav>
          </header>

          {children}

          <footer className="p-10">
            <p>Feito com Next.js 13.4</p>
          </footer>
        </div>
      </body>
    </html>
  )
}
